<?php
/**
 * @var $block \AlyaPay\Payment\Block\Product\CreditPromotion
 */
?>
<div class="alyapay-credit-promo">
    <alya-placement key="credit-promotion"
                    price="<?= $block->escapeHtmlAttr($block->getWidgetPrice()) ?>"
                    currency="<?= $block->escapeHtmlAttr($block->getWidgetCurrency()) ?>"
                    lang="<?= $block->escapeHtmlAttr($block->getWidgetLang()) ?>"
                    installments="4"
                    theme="<?= $block->escapeHtmlAttr($block->getWidgetTheme()) ?>"
                    variant="<?= $block->escapeHtmlAttr($block->getWidgetVariant()) ?>"
                    detail="<?= $block->escapeHtmlAttr($block->getWidgetDetail()) ?>"
                    logo-position="<?= $block->escapeHtmlAttr($block->getWidgetLogoPosition()) ?>"></alya-placement>
</div>
