<?php
/**
 * @var $block \AlyaPay\Payment\Block\Cart\CreditPromotion
 */
?>
<div class="alyapay-credit-promo">
    <alya-placement key="credit-promotion"
                    price="<?= $block->escapeHtmlAttr($block->getWidgetPrice()) ?>"
                    currency="<?= $block->escapeHtmlAttr($block->getWidgetCurrency()) ?>"
                    theme="<?= $block->escapeHtmlAttr($block->getWidgetTheme()) ?>"
                    lang="<?= $block->escapeHtmlAttr($block->getWidgetLang()) ?>"
                    installments="4"></alya-placement>
</div>
